# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Logger Plugin                        /
# /                                                           /
# /////////////////////////////////////////////////////////////
# Thank you for using Logger Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
# Spigot: Prism3
# Discord: Prism3#5787 | ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX
Server-Name: "Server_Name"
File-Deletion: 7
Log-to-Files: true
Staff:
  Enabled: false
Log:
  Player-Chat: true
  Player-Commands: true
  Console-Commands: true
  Player-Sign-Text: true
  Player-Join: true
  Player-Leave: true
  Player-Kick: true
  Player-Death: true
  Player-Teleport: true
  Player-Level: true
  Block-Place: true
  Block-Break: true
  Portal-Creation: true
  Bucket-Place: true
  Anvil: true
  TPS: true
  RAM: true
  Server-Start: true
  Server-Stop: true
  Item-Pickup: true
  Item-Drop: true
  Enchanting: true
  Book-Editing: true
  AFK: true
  Furnace: true
  Primed-TNT: true
RAM-TPS-Checker: 6000
TPS:
  Value-Medium: 16
  Value-Critical: 7
RAM:
  Percent: 50
Player-Level:
  Log-Above: 100
Player-Commands:
  Whitelist-Commands: false
  Commands-to-Log:
    - /msg
    - /sell
    - /plugins
    - /pl
    - /about
  Blacklist-Commands: true
  Commands-to-Block:
    - /login
    - /changepassword
    - /register
  Commands-Spy:
    Enable: false
    Message: "&8[&bLogger &8&l| &eSpy&8] &7%player% >> %cmd%"
Player-Join:
  Player-IP: true
Item-Pickup:
  - "APPLE"
  - "BARRIER"
  - "BEDROCK"
MySQL:
  Enable: false
  Host: localhost
  Port: 3306
  Username: username
  Password: PassworD
  Database: database
  Data-Deletion: 7
SQLite:
  Enable: false
  Data-Deletion: 7