name: Logger
version: ${project.version}
main: me.prism3.logger.Main
api-version: 1.13
authors: [ Prism3 , thelooter ]
description: Log all Activities from Players and Server Side!
softdepend: [Essentials, AuthMe, Vault]
commands:
  logger:
    description: "Plugin command."
  logger reload:
    description: "Reloads the Plugin configs."
  logger credits:
    description: "Shows the Plugin authors."
permissions:
  logger.staff:
    description: "Allows the Player to execute Plugin Commands, spy on others actions, and view Plugin Updates."
    default: op
    children:
      logger.exempt: true
      logger.reload: true
      logger.spy: true
      logger.update: true
  logger.exempt:
    description: "Prevents the Player from getting logged."
    default: op
    children:
      logger.exempt.discord: true
  logger.exempt.discord:
    description: "Prevents the Player from getting discord logged."
  logger.reload:
    description: "Allows to Reload the Plugin."
    default: op
  logger.spy:
    description: "Ability to see other players' and Staff's actions."
    default: op
  logger.spy.bypass:
    description: "Ability to see other players and staff's Actions but others can not."
    default: op
    children:
      logger.spy: true
  logger.staff.log:
    description: "Logs Staff Members."
    children:
      logger.exempt: false
  logger.update:
    description: "Ability to receive Plugin Updates."
    default: op