name: Logger
version: ${project.version}
main: com.carpour.logger.Main
api-version: 1.13
authors: [ Prism3 , thelooter ]
description: Log all Activities from Commands, Chat, Player Join, Player Leave, Player Death and even Server's RAM, TPS and Much More!
softdepend: [Essentials]
commands:
  logger:
    description: Plugin Command.
  logger reload:
    description: Reloads the plugin Configs.
  logger credits:
    description: Shows the plugin Authors.
permissions:
  logger.staff:
    description: Allows the user to view Plugin Updates.
    default: op
    children:
      logger.exempt: true
      logger.reload: true
      logger.cmdspy: true
      logger.update: true
  logger.exempt:
    description: Prevents the Player from Getting Logged.
    default: op
  logger.reload:
    description: Allows to Reload the Plugin.
    default: op
  logger.cmdspy:
    description: Ability to see other player's Commands.
    default: op
  logger.staff.log:
    description: Logs Staff Members.
  logger.update:
    description: Update Message is sent to the Users with this Permission.